package com.quarkbyte.recoveryappjava.model.enums.csj;

public enum InternalStatus {
    CASO_NOVO, EM_RECUPERACAO, FINALIZADO, NAO_RECUPERADO, NEGOCIANDO, PAGO, RECUPERADO, RECUPERADO_USUARIO,
    REPARADO_FRANQUIA, ACOMPANHAR, SEM_ACORDO, SENDO_PROCESSADO, TROCADO_GARANTIA
}