package com.quarkbyte.recoveryappjava.model.enums.csj;

public enum ResolutionType {
    CHARGEBACK_PAGO, COMPRA, COMPRA_MAIS_MULTA, CREDITO_MAIS_COMPLEMENTO, DEBITO, DEBITO_MAIS_COMPLEMENTO,
    DEVOLUCAO, DEVOLUCAO_MAIS_MULTA, DEVOLUCAO_MAIS_REPARO, ESTORNO, PAGAMENTO_DE_REPARO, RECORRENCIA_PAGA,
    RENOVACAO, RENOVACAO_MAIS_UM_REAL, RENOVACAO_MAIS_MULTA, RENOVACAO_MAIS_MULTA_MAIS_UM_REAL, RESSARCIMENTO,
    RESSARCIMENTO_MAIS_MULTA, TAXA_DE_ATIVACAO_DE_SINISTRO_PAGA
}